### ISSUE TITLE
NioDatagramAcceptorExIT#shouldConnect fails

### ISSUE THREAD

**Issue by jitsni** [kaazing/gateway#153]
Running org.apache.mina.transport.socket.nio.NioDatagramAcceptorExIT
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.038 sec <<< FAILURE! - in org.apache.mina.transport.socket.nio.NioDatagramAcceptorExIT
shouldConnect(org.apache.mina.transport.socket.nio.NioDatagramAcceptorExIT)  Time elapsed: 0.038 sec  <<< FAILURE!
java.lang.AssertionError: not all expectations were satisfied
expectations:
  ! expected once, never invoked: ioHandler.sessionCreated(instance of org.kaazing.mina.core.session.IoSessionEx)
  ! expected once, never invoked: ioHandler.sessionOpened(instance of org.kaazing.mina.core.session.IoSessionEx)
  ! expected once, never invoked: ioHandler.messageReceived(instance of org.kaazing.mina.core.session.IoSessionEx, <HeapBuffer[pos=0 lim=4 cap=4: 74 65 78 74]>)
  ! expected once, never invoked: ioHandler.sessionClosed(instance of org.kaazing.mina.core.session.IoSessionEx)
what happened before this: nothing!
	at org.jmock.lib.AssertionErrorTranslator.translate(AssertionErrorTranslator.java:20)
	at org.jmock.Mockery.assertIsSatisfied(Mockery.java:199)
	at org.jmock.integration.junit4.JUnitRuleMockery$1.evaluate(JUnitRuleMockery.java:50)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Comment by sbadugu** [comment]
Pull request: #184 didn't pass the build and gave the following error:

[Log file](https://s3.amazonaws.com/archive.travis-ci.org/jobs/66069438/log.txt)

```
Failed tests: 
  NioDatagramAcceptorExIT.shouldConnect not all expectations were satisfied
expectations:
  ! expected once, never invoked: ioHandler.sessionCreated(instance of org.kaazing.mina.core.session.IoSessionEx)
  ! expected once, never invoked: ioHandler.sessionOpened(instance of org.kaazing.mina.core.session.IoSessionEx)
  ! expected once, never invoked: ioHandler.messageReceived(instance of org.kaazing.mina.core.session.IoSessionEx, <HeapBuffer[pos=0 lim=4 cap=4: 74 65 78 74]>)
  ! expected once, never invoked: ioHandler.sessionClosed(instance of org.kaazing.mina.core.session.IoSessionEx)
what happened before this: nothing!

Tests run: 39, Failures: 1, Errors: 0, Skipped: 2

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:verify (default) on project mina.netty: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/travis/build/kaazing/gateway/mina.netty/target/failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :mina.netty
travis_time:end:2681fc52:start=1433864909750788196,finish=1433865021367869126,duration=111617080930
[0K
[31;1mThe command "mvn -q clean verify" exited with 1.[0m

Done. Your build exited with 1.
```

**Comment by sbadugu** [comment]
This should be fixed in UDP Spec tests
