### ISSUE TITLE
Long start time on systems with low entropy (containers) due to calls to getSecureBytes.

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/gateway#167]
This is due to calls on getSecureBytes which by default Java uses /dev/random.  dev/random is populated by the entropy of the system and is a [blocking call](http://en.wikipedia.org/?title=/dev/random).

```
"main" #1 prio=5 os_prio=0 tid=0x00007fa8f000b000 nid=0x7 runnable [0x00007fa8f78cf000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at sun.security.provider.SeedGenerator$URLSeedGenerator.getSeedBytes(SeedGenerator.java:539)
	at sun.security.provider.SeedGenerator.generateSeed(SeedGenerator.java:144)
	at sun.security.provider.SecureRandom$SeederHolder.<clinit>(SecureRandom.java:203)
	at sun.security.provider.SecureRandom.engineNextBytes(SecureRandom.java:221)
	- locked <0x00000000f5f95c80> (a sun.security.provider.SecureRandom)
	at java.security.SecureRandom.nextBytes(SecureRandom.java:468)
	- locked <0x00000000f5f95fa0> (a java.security.SecureRandom)
	at org.snmp4j.security.Salt.<init>(Salt.java:55)
	at org.snmp4j.security.Salt.getInstance(Salt.java:80)
	at org.snmp4j.security.PrivDES.<init>(PrivDES.java:57)
	at org.snmp4j.security.SecurityProtocols.addDefaultProtocols(SecurityProtocols.java:152)
	- locked <0x00000000f5f775f8> (a org.snmp4j.security.SecurityProtocols)
	at org.kaazing.gateway.management.snmp.SnmpManagementServiceHandler$KaazingConfigManager.getSupportedSecurityProtocols(SnmpManagementServiceHandler.java:910)
	at org.kaazing.gateway.management.snmp.SnmpManagementServiceHandler$KaazingConfigManager.createUSM(SnmpManagementServiceHandler.java:920)
	at org.kaazing.gateway.management.snmp.SnmpManagementServiceHandler$KaazingConfigManager.initSecurityModels(SnmpManagementServiceHandler.java:726)
	at org.kaazing.gateway.management.snmp.SnmpManagementServiceHandler$KaazingConfigManager.initialize(SnmpManagementServiceHandler.java:1014)
	at org.kaazing.gateway.management.snmp.SnmpManagementServiceHandler.<init>(SnmpManagementServiceHandler.java:227)
	at org.kaazing.gateway.management.snmp.SnmpManagementService.init(SnmpManagementService.java:104)
	at org.kaazing.gateway.server.context.resolve.DefaultServiceContext.init(DefaultServiceContext.java:1013)
	at org.kaazing.gateway.server.Launcher.initInternal(Launcher.java:78)
	at org.kaazing.gateway.server.Launcher.init(Launcher.java:54)
	at org.kaazing.gateway.server.impl.GatewayImpl.launch(GatewayImpl.java:308)
	at org.kaazing.gateway.server.GatewayCommandLineProcessor.launchGateway(GatewayCommandLineProcessor.java:105)
	at org.kaazing.gateway.server.GatewayCommandLineProcessor.launchGateway(GatewayCommandLineProcessor.java:51)
	at org.kaazing.gateway.server.Main.main(Main.java:43)

```

**Comment by dpwspoon** [comment]
dev/urandom seems to be a suitable, that does not block (instead it uses the previous seed if there has not been enough entropy to generate a new seed).  These two posts seem to state that it is sufficiently secure ([post1](http://security.stackexchange.com/questions/3936/is-a-rand-from-dev-urandom-secure-for-a-login-key) and [post2](http://www.2uo.de/myths-about-urandom/))

**Comment by dpwspoon** [comment]
One solution is to start docker with `docker run --rm -h gateway -p 8000:8000 -v /dev/urandom:/dev/random kaazing/gateway:latest`.  But this maps to the physical host and is only a solution for docker, where as the issue could occur on any VM or container.  

A generic java solution is to add `-Djava.security.egd=file:/dev/./urandom` to the startup script
