### ISSUE TITLE
AgronaMonitoringEntityFactoryTest fails the build (on Mac OS x)

### ISSUE THREAD

**Issue by jitsni** [kaazing/gateway#171]
The following test fails on mac. It is checking whether the following dir exists or not.

Monitoring Dir = /var/folders/16/n6m82d_13bvb7kfwnt9llhd40000gn/T/\kaazing

---------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.172 sec <<< FAILURE!
testAgronaLifecycle(org.kaazing.gateway.management.monitoring.entity.impl.AgronaMonitoringEntityFactoryTest)  Time elapsed: 0.131 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.kaazing.gateway.management.monitoring.entity.impl.AgronaMonitoringEntityFactoryTest.testAgronaLifecycle(AgronaMonitoringEntityFactoryTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Results :

Failed tests:   testAgronaLifecycle(org.kaazing.gateway.management.monitoring.entity.impl.AgronaMonitoringEntityFactoryTest)

**Comment by irina-mitrea-luxoft** [comment]
Added a pull request for this issue at: https://github.com/kaazing/gateway/pull/190

Important: the fix should be tested under Mac OS prior to merging the change. I was unable to test this fix under Mac OS due to the fact that I have no access to such an environment.

Thank you.

**Comment by irina-mitrea-luxoft** [comment]
Can I attempt to test on one of the environments below from ([Autonomous build] (https://docs.google.com/spreadsheets/d/1lHVydPw0miEbJReX-Wwxd-8uWdc3L15GF5CAtYZmDkk/edit#gid=1))?

Build MacMini	build-macmini.kaazing.wan	192.168.5.30	MacOS 10.7
Build MacMini 2	build-macmini2.kaazing.wan	192.168.4.48	MacOS
Build MacMini 3	build-macmini3.kaazing.wan	192.168.5.19	MacOS 10.9

I am asking this because testing the unit test referred in this issue on one of the hosts above would imply a checkout of my fork on one of these hosts and I am unsure as to these hosts' status.

**Comment by irina-mitrea-luxoft** [comment]
Tested under Mac OS - the pull request can now be reviewed.
