### ISSUE TITLE
Unexpected exception in org.apache.mina.core.IoServiceListenerSupportTest

### ISSUE THREAD

**Issue by brennangaunce** [kaazing/gateway#173]
Test appears to fail on mac, but exception does not cause test failure:

```
Running org.apache.mina.core.IoServiceListenerSupportTest
[21:50:39] WARN [org.apache.mina.core.filterchain.DefaultIoFilterChain] - Unexpected exception from exceptionCaught handler.
java.lang.AssertionError: 
  Unexpected method call exceptionCaught((0x00000030: mina dummy, server, ? => 0.0.0.0/0.0.0.0:8080), java.lang.AssertionError: 
  Unexpected method call sessionClosed((0x00000030: mina dummy, server, ? => 0.0.0.0/0.0.0.0:8080)):
    sessionClosed((0x00000030: mina dummy, server, ? => 0.0.0.0/0.0.0.0:8080)): expected: 1, actual: 1 (+1)):
    at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:29)
    at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:56)
    at com.sun.proxy.$Proxy8.exceptionCaught(Unknown Source)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.exceptionCaught(DefaultIoFilterChain.java:694)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextExceptionCaught(DefaultIoFilterChain.java:483)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1100(DefaultIoFilterChain.java:49)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.exceptionCaught(DefaultIoFilterChain.java:788)
    at org.apache.mina.core.filterchain.IoFilterAdapter.exceptionCaught(IoFilterAdapter.java:111)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextExceptionCaught(DefaultIoFilterChain.java:483)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireExceptionCaught(DefaultIoFilterChain.java:471)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionClosed(DefaultIoFilterChain.java:400)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$900(DefaultIoFilterChain.java:49)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.sessionClosed(DefaultIoFilterChain.java:778)
    at org.apache.mina.core.filterchain.IoFilterAdapter.sessionClosed(IoFilterAdapter.java:95)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionClosed(DefaultIoFilterChain.java:398)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireSessionClosed(DefaultIoFilterChain.java:391)
    at org.apache.mina.core.service.IoServiceListenerSupport.fireSessionDestroyed(IoServiceListenerSupport.java:210)
    at org.apache.mina.core.IoServiceListenerSupportTest$1.run(IoServiceListenerSupportTest.java:192)
```

**Comment by eciuca** [comment]
Did you find anything else connected to this error?
