### ISSUE TITLE
WsebAcceptorTest.shouldBindAWsAddress timeouts

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/gateway#287]
from [TravisCI build](https://s3.amazonaws.com/archive.travis-ci.org/jobs/76321584/log.txt)

**Comment by dpwspoon** [comment]
and wsr is failing [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/76358721/log.txt)

**Comment by jitsni** [comment]
Exception from travis build
```
shouldBindAWsAddress(org.kaazing.gateway.transport.wseb.WsebAcceptorTest)  Time elapsed: 5.029 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 5 seconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.jboss.netty.channel.DefaultChannelFuture.awaitUninterruptibly(DefaultChannelFuture.java:259)
	at org.kaazing.mina.netty.ChannelIoAcceptor.unbind0(ChannelIoAcceptor.java:200)
	at org.kaazing.mina.core.service.AbstractIoAcceptor.unbind(AbstractIoAcceptor.java:390)
	at org.kaazing.mina.core.service.AbstractIoAcceptor.unbind(AbstractIoAcceptor.java:325)
	at org.kaazing.mina.netty.ChannelIoAcceptor.dispose0(ChannelIoAcceptor.java:244)
	at org.kaazing.mina.core.service.AbstractIoService.dispose(AbstractIoService.java:308)
	at org.kaazing.gateway.transport.nio.internal.AbstractNioAcceptor.dispose(AbstractNioAcceptor.java:460)
	at org.kaazing.gateway.transport.nio.internal.NioSocketAcceptor.dispose(NioSocketAcceptor.java:167)
	at org.kaazing.gateway.transport.wseb.WsebAcceptorTest.disposeConnector(WsebAcceptorTest.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sbadugu** [comment]
@dpwspoon Is this still an issue ? If not, can we close it ?
