### ISSUE TITLE
Sporadic Travis build failure in random tests due to hang during Gateway shutdown

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#292]
The Gateway builds on Travis are frequently failing due to hangs. The addition of a Timeout rule to most tests with option "look for stuck thread" has revealed that this is sometimes if not always occurring during Gateway shut down. This can be seen for example from the log for https://travis-ci.org/kaazing/gateway/builds/76702937. Here is an extract:
```
testNoJMXBindingNameConflictsOnMultiServicesUsingSameConnect(org.kaazing.gateway.management.jmx.JmxManagementServiceHandlerTest)  Time elapsed: 20.004 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 20 seconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.jboss.netty.channel.DefaultChannelFuture.awaitUninterruptibly(DefaultChannelFuture.java:259)
	at org.kaazing.mina.netty.ChannelIoAcceptor.unbind0(ChannelIoAcceptor.java:200)
	at org.kaazing.mina.core.service.AbstractIoAcceptor.unbind(AbstractIoAcceptor.java:390)
	at org.kaazing.mina.core.service.AbstractIoAcceptor.unbind(AbstractIoAcceptor.java:325)
	at org.kaazing.mina.netty.ChannelIoAcceptor.dispose0(ChannelIoAcceptor.java:244)
	at org.kaazing.mina.core.service.AbstractIoService.dispose(AbstractIoService.java:308)
	at org.kaazing.gateway.transport.nio.internal.AbstractNioAcceptor.dispose(AbstractNioAcceptor.java:460)
	at org.kaazing.gateway.transport.nio.internal.NioSocketAcceptor.dispose(NioSocketAcceptor.java:167)
	at org.kaazing.gateway.server.context.resolve.DefaultTransportContext.dispose(DefaultTransportContext.java:109)
	at org.kaazing.gateway.server.context.resolve.DefaultGatewayContext.dispose(DefaultGatewayContext.java:124)
	at org.kaazing.gateway.server.Launcher.destroy(Launcher.java:140)
	at org.kaazing.gateway.server.test.Gateway.stop(Gateway.java:294)
	at org.kaazing.gateway.management.jmx.JmxManagementServiceHandlerTest.testNoJMXBindingNameConflictsOnMultiServicesUsingSameConnect(JmxManagementServiceHandlerTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

This is very likely the underlying cause of #197.

**Comment by sbadugu** [comment]
Issue moved to [kaazing/tickets #379](https://github.com/kaazing/tickets/issues/379) via [**ZenHub.io**](https://www.zenhub.io/)
