### ISSUE TITLE
gateway.transport.wsn: IdleTimeoutExtensionPongsIT.shouldGetPongsFromidleTimeoutExtensionWhenWriterIdle spurious failures

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/gateway#34]
On a fresh CentOS instance (installed maven 3.2.3, openjdk 1.7.0_71) the IdleTimeoutExtensionPongsIT.shouldGetPongsFromidleTimeoutExtensionWhenWriterIdle fails intermittently.  I built the test 4 times and received 3 failures.

```
-------------------------------------------------------------------------------
Test set: org.kaazing.gateway.transport.wsn.extensions.idletimeout.IdleTimeoutExtensionPongsIT
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.273 sec <<< FAILURE!
shouldGetPongsFromidleTimeoutExtensionWhenWriterIdle(org.kaazing.gateway.transport.wsn.extensions.idletimeout.IdleTimeoutExtensionPongsIT)  Time elapsed: 3.268 sec  <<< FAILURE!
org.junit.ComparisonFailure: Robotic behavior did not match expected expected:<... (frequent enough)

[write await SLEEP_ONE
write [0x81 0x83 0x01 0x01 0x01 0x01 0x30 0x33 0x32]

write await SLEEP_TWO
write [0x81 0x83 0x01 0x01 0x01 0x01 0x30 0x33 0x32]

write await SLEEP_THREE
write [0x81 0x83 0x01 0x01 0x01 0x01 0x30 0x33 0x32]

write await SLEEP_FOUR
write [0x81 0x83 0x01 0x01 0x01 0x01 0x30 0x33 0x32]

write await SLEEP_FIVE
write [0x81 0x83 0x01 0x01 0x01 0x01 0x30 0x33 0x32]

write await SLEEP_SIX
write [0x81 0x83 0x01 0x01 0x01 0x01 0x30 0x33 0x32]

write await SLEEP_SEVEN
write [0x81 0x83 0x01 0x01 0x01 0x01 0x30 0x33 0x32]

write await SLEEP_EIGHT
write [0x81 0x83 0x01 0x01 0x01 0x01 0x30 0x33 0x32]

# Expect (extension) PONG
read [0x81 0x06 0x01 0x01 0x01 0x02 0x0a 0x00]


# Do clean close
write [0x88 0x00]
read [0x88 0x00]

close
closed

# Connection from back end of proxy service
# =========================================
accept tcp://127.0.0.1:8002
accepted
connected
# read 8 "abc" frames
read [0x31 0x32 0x33]
read [0x31 0x32 0x33]
read [0x31 0x32 0x33]
read [0x31 0x32 0x33]
read [0x31 0x32 0x33]
read [0x31 0x32 0x33]
read [0x31 0x32 0x33]
read [0x31 0x32 0x33]
closed

# Connect to ServerSocket in test method to read period data to simulate SLEEP
# ============================================================================
connect tcp://localhost:61234
connected
read "WakeUp1"
read notify SLEEP_ONE
read "WakeUp2"
read notify SLEEP_TWO
read "WakeUp3"
read notify SLEEP_THREE
read "WakeUp4"
read notify SLEEP_FOUR
read "WakeUp5"
read notify SLEEP_FIVE
read "WakeUp6"
read notify SLEEP_SIX
read "WakeUp7"
read notify SLEEP_SEVEN
read "WakeUp8"
read notify SLEEP_EIGHT
close
closed]
> but was:<... (frequent enough)
[[id: 0xff0937ae, /127.0.0.1:60170 => /127.0.0.1:8001] RECEIVED: BigEndianHeapChannelBuffer(ridx=0, widx=8, cap=8)
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 81 06 01 01 01 02 09 00                         |........        |
+--------+-------------------------------------------------+----------------+

# Connection from back end of proxy service
# =========================================
accept tcp://127.0.0.1:8002
accepted
connected
# read 8 "abc" frames
[id: 0x7a23f384, /127.0.0.1:37075 :> /127.0.0.1:8002] DISCONNECTED

# Connect to ServerSocket in test method to read period data to simulate SLEEP
# ============================================================================
connect tcp://localhost:61234
[id: 0xb2327577] CLOSED]
>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.kaazing.robot.junit.rules.RoboticStatement.evaluate(RoboticStatement.java:115)
        at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:104)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
```

**Comment by krismcqueen** [comment]
My assumption is this is exactly the race condition I experienced when dealing with the specification.tcp & nuklei integration.  I will modify this test and update the project to the latest robot to have the test be deterministic.

**Comment by krismcqueen** [comment]
Closed by https://github.com/kaazing/gateway/pull/39

As previously stated, this was a race condition between the thread that bound the port and the thread that connected to the port in the particular test.  The repository was updated to the latest robot which has the start/finish semantics in K3PO, the test was updated to use those semantics, and now things pass.
