### ISSUE TITLE
Java 7 throws unfriendly error

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/gateway#351]
The gateway only runs with java 8 and is suppose to throw a warning saying to run with Java 8 if someone is running with Java 7.  However, the error it throws doesn't make sense / isn't intuitive (Here is a copy from ubuntu java 7 .79

```

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/kaazing/gateway/server/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
kaazing@Kaazing-Proxy-vcenter:~/kaazing-gateway-community-5.0.1.34$ cat log/ehistory^C
kaazing@Kaazing-Proxy-vcenter:~/kaazing-gateway-community-5.0.1.34$ history

```

**Comment by sbadugu** [comment]
It's a very cosmetic fix. We can reopen it if we decide to fix it.
