### ISSUE TITLE
BroadcastServiceTest.testSlowConsumer() is timing out

### ISSUE THREAD

**Issue by sanjay-saxena** [kaazing/gateway#364]
Here is the stack trace:

```
java.lang.Exception: Appears to be stuck in thread New I/O worker #3
        at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
        at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
        at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.jboss.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:83)
```

Attaching surefire reports:

[org.kaazing.gateway.service.broadcast.BroadcastServiceTest.txt](https://files.zenhub.io/565f8c58b090a1f14a950a55)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
[TEST-org.kaazing.gateway.service.broadcast.BroadcastServiceTest.xml](https://files.zenhub.io/565f8c58b090a1f14a950a56)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by sanjay-saxena** [comment]
This can reproduced consistently on Mac OSX 10.10.

**Comment by sbadugu** [comment]
This should have been fixed and currently not reproducible.

**Comment by dpwspoon** [comment]
We saw this again today
