### ISSUE TITLE
wse transport sometimes fails with "Attempt to read into suspended session that already has a current read request"

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#421]
Emulated WebSocket transport layer sometimes fails while a connection is being established to WsebAcceptor, with the following exception:
```
1169 transport.tcp.accept [New I/O worker #34] INFO  accept  - [tcp#49 127.0.0.1:59284] EXCEPTION: java.lang.Exception: Read error. Attempt
to read into suspended session that already has a current read request
java.lang.Exception: Read error. Attempt to read into suspended session that already has a current read request
        at org.kaazing.gateway.transport.http.HttpAcceptor$3.fireContentReceived(HttpAcceptor.java:505)
        at org.kaazing.gateway.transport.http.HttpAcceptor$3.doMessageReceived(HttpAcceptor.java:468)
        at org.kaazing.gateway.transport.http.HttpAcceptor$3.doMessageReceived(HttpAcceptor.java:305)
        at org.kaazing.gateway.transport.IoHandlerAdapter.messageReceived(IoHandlerAdapter.java:45)
```
Test case WsebRealignmentIT, to be merged as part of PR https://github.com/kaazing/gateway/pull/418, reproduces the issue. Gateway trace log is available here:
[WsebRealignmentIT_fail.out](https://files.zenhub.io/56bbe8e04bb8ca1d55c4cb88)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by cmebarrow** [comment]
Fixed by PR https://github.com/kaazing/gateway/pull/418
