### ISSUE TITLE
Gateway Travis build failed in wseb transport, 3 test failures

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#424]
See [build 1173](https://s3.amazonaws.com/archive.travis-ci.org/jobs/108914259/log.txt). Failures were

1. org.kaazing.gateway.transport.wseb.specification.wse.connector.OpeningIT.shouldEstablishConnectionWithRequestHeaderXWebSocketProtocol FAILED with exception java.lang.AssertionError: unexpected invocation: ioHandler.exceptionCaught

1. org.kaazing.gateway.transport.wseb.specification.wse.acceptor.TextIT.clientSendTextInvalidUTF8 FAILED with exception org.junit.ComparisonFailure: downstream content type was text instead of octet-stream. 

1. org.kaazing.gateway.transport.wseb.specification.wse.acceptor.ProxiesIT.shouldReceiveDataFromServerOnLongpollingRequest FAILED with exception java.net.SocketTimeoutException: Read timed out

1. WsebConnectorLoggingIT.shouldLogProtocolException FAILED with exception java.lang.AssertionError: not all expectations were satisfied...
  ! expected once, never invoked: ioHandler.sessionClosed(an instance of org.kaazing.mina.core.session.IoSessionEx)

**Comment by cmebarrow** [comment]
Number 4 looks like a testware issue. The log messages show that the sessionClosed event was fired. It just wasn't picked up in time at the JMock level for some reason, probably related to threading although we are calling setThreadingPolicy(new Synchroniser()) on the JMock context.

**Comment by cmebarrow** [comment]
Number 2 looks like a race between closing the wseb session and processing the downstream request. We are probably entering the "if (wsebSession.isClosing())" statement at the start of WsebDownstreamHandler.doSessionOpened and so closing the downstream http session abruptly with the wrong (default) content type. Fix would be to change the condition to "if (wsebSession.getTransport().isClosing())"

**Comment by cmebarrow** [comment]
Number 3 is due to a timing issue in the test. The rase is between the junit test method is writing "data1" to the wsebSession and the client script issuing the overlapping downstream request. In this test run the latter won the race so "data1" and that being written to the overlapping downstream instead of the first downstream, causing the test to hang waiting for a barrier in the script which is never notified.

**Comment by cmebarrow** [comment]
Number 1 is happening because of a bug in WsebConnector.createHandler.doSessionClosed. It is erroneously assuming createSession.getWriteHeaders(HEADER_X_WEBSOCKET_PROTOCOL) will return a list of the individual values in the X-WebSocket-Protocol write header, but that is not the case when that header was set using setWriteHeader("primary, secondary") because DefaultHttpSession has no logic to split up the header value.
This test should always be failing (on all platforms, not just Travis), but is not. So there is an issue with the test as well.

**Comment by cmebarrow** [comment]
Fixes for failures 1,2 and 4 are ready in my gateway branch issue_gateway_424. It requires wse spec changes from my k3po branch more_wse_spec_fixes

**Comment by cmebarrow** [comment]
With the above fixes we now got other failures on Travis:
[Travis_Gateway_Build_1179_1_wseb_fails.out](https://files.zenhub.io/56c4fde35d3a5c4e4bb3cfec)

- DownstreamIT.shouldCloseConnectionWhenBinaryDownstreamResponseContentTypeHasUnexpectedValue FAILED with sessionClosed expectation not met. This is an issue with the test: need to wait for sessionClosed to fire.
- OpeningIT.shouldEstablishConnection FAILED with unexpected handler.exceptionCaught. This is again an issue with the test: exception caught will quite correctly have fired if k3po closes the transport before the JMock context is verified. Fixing the test to explicitly call session.close so we don't get an exception.

**Comment by cmebarrow** [comment]
The following they also sometimes happens (in Travis and on Mac):
- ClosingIT.clientAbruptlyClosesUpstream (acceptor) 
```
Specified behavior did not match expected:<...UPSTREAM_ABORT
read [[0x01 0x30 0x32 0xFF]
read [0x01 0x30 0x31 0xFF]
read closed

]closed

# Upstream
c...> but was:<...UPSTREAM_ABORT
read []closed

# Upstream
c...>
```
This occurred twice (cmebarrow/gateway build #78). The reason is timing of the upstream and downstream requests. This failure is occurring because we fall into the following if condition in WsebDownstreamHandler.reconnSession:
```
 if (wsebSession == null || wsebSession.isClosing()) {
            session.close(false);
            return;
        }
```
Fix is to write the WS CLOSE and RECONNECT commands before closing the session.

**Comment by cmebarrow** [comment]
With the above fix the test still failed on one run. Console output is here:
[ClosingIT.clientAbruptlyClosesUpstream.fail.with.fix.txt](https://files.zenhub.io/56c64be45d3a5c4e4bb3efdd)
The following extract indicates the problem is due to the closed event arriving while the upstream is being realigned:
```
28842 transport.http.accept [New I/O worker #1653] INFO  accept  - [http#365 wseb#359u 127.0.0.1:51862] OPENED: (#00000365: kzg http, server, http://localhost:8080/path/;e/ubm/s5k8Hc1YhIbViOwn95Skact9t615Kp5j?query => http://localhost:8080/path/;e/ubm/s5k8Hc1YhIbViOwn95Skact9t615Kp5j)
28843 org.kaazing.mina.core.util.Util [New I/O worker #1653] ERROR Util  - org.kaazing.mina.core.service.AbstractIoProcessor.remove(AbstractIoProcessor.java:60): expected current thread Thread[New I/O worker #1653,5,FailOnTimeoutGroup] to match Thread[Thread-3,5,FailOnTimeoutGroup] in session (#00000362: kaazing niosocketchannel, server, /127.0.0.1:51862 => /127.0.0.1:8080)
java.lang.RuntimeException: expected current thread Thread[New I/O worker #1653,5,FailOnTimeoutGroup] to match Thread[Thread-3,5,FailOnTimeoutGroup] in session (#00000362: kaazing niosocketchannel, server, /127.0.0.1:51862 => /127.0.0.1:8080)
	at org.kaazing.mina.core.util.Util.verifyInIoThread(Util.java:33)
	at org.kaazing.mina.core.service.AbstractIoProcessor.remove(AbstractIoProcessor.java:60)
	at org.kaazing.mina.core.service.AbstractIoProcessor.remove(AbstractIoProcessor.java:30)
	at org.kaazing.mina.netty.IoSessionChannelHandler.channelClosed(IoSessionChannelHandler.java:69)
	at org.jboss.netty.channel.Channels.fireChannelClosed(Channels.java:468)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:424)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:148)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:144)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:348)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:120)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cmebarrow** [comment]
Resolved by PR https://github.com/kaazing/gateway/pull/426. ClosingIT.clientAbruptlyClosesUpstream is marked ignored pending resolution of #427.
