### ISSUE TITLE
Exception sometimes occurs using emulated WebSocket: RuntimeException expected current thread ... to match ...

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#427]
This condition can happen if a client abruptly closes the transport of a newly issued downstream or upstream request for an emulated WebSocket connection. It can be reproduced by running wseb transport acceptor specification test ClosingIT.clientAbruptlyClosesUpstream after adding a 2000 millisecond sleep WsebSession.attachWriter at the start of the run() method of the executed task that called attachWriter0.
```
28842 transport.http.accept [New I/O worker #1653] INFO  accept  - [http#365 wseb#359u 127.0.0.1:51862] OPENED: (#00000365: kzg http, server, http://localhost:8080/path/;e/ubm/s5k8Hc1YhIbViOwn95Skact9t615Kp5j?query => http://localhost:8080/path/;e/ubm/s5k8Hc1YhIbViOwn95Skact9t615Kp5j)
28843 org.kaazing.mina.core.util.Util [New I/O worker #1653] ERROR Util  - org.kaazing.mina.core.service.AbstractIoProcessor.remove(AbstractIoProcessor.java:60): expected current thread Thread[New I/O worker #1653,5,FailOnTimeoutGroup] to match Thread[Thread-3,5,FailOnTimeoutGroup] in session (#00000362: kaazing niosocketchannel, server, /127.0.0.1:51862 => /127.0.0.1:8080)
java.lang.RuntimeException: expected current thread Thread[New I/O worker #1653,5,FailOnTimeoutGroup] to match Thread[Thread-3,5,FailOnTimeoutGroup] in session (#00000362: kaazing niosocketchannel, server, /127.0.0.1:51862 => /127.0.0.1:8080)
	at org.kaazing.mina.core.util.Util.verifyInIoThread(Util.java:33)
	at org.kaazing.mina.core.service.AbstractIoProcessor.remove(AbstractIoProcessor.java:60)
	at org.kaazing.mina.core.service.AbstractIoProcessor.remove(AbstractIoProcessor.java:30)
	at org.kaazing.mina.netty.IoSessionChannelHandler.channelClosed(IoSessionChannelHandler.java:69)
	at org.jboss.netty.channel.Channels.fireChannelClosed(Channels.java:468)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:424)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:148)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:144)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:348)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:120)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by cmebarrow** [comment]
Fixed by PR https://github.com/kaazing/gateway/issues/427
