### ISSUE TITLE
Gateway build failing in ssl transport: VirtualHostKeySelectorTest when etc/hosts has the entries required by the test

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#457]
To reproduce (in checked out gateway):
- Edit /etc/hosts file (or c:\windows\system32\drivers\etc\hosts on Windows) to add entries
```
127.0.0.1   one.kaazing.test
127.0.0.1   two.kaazing.test
127.0.0.1   one.example.test
127.0.0.1   two.example.test
127.0.0.1   three.example.test
```
- mvn clean install
Output:
```
Running org.kaazing.gateway.transport.ssl.VirtualHostKeySelectorTest
Tests run: 11, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.628 sec <<< FAILURE!
shouldGetVirtualHostMatchingHostAlias(org.kaazing.gateway.transport.ssl.VirtualHostKeySelectorTest)  Time elapsed: 0.016 sec  <<< ERROR!
java.lang.ClassCastException: java.net.URI cannot be cast to java.lang.String
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.parseNamedOptions(ResourceAddressFactorySpi.java:370)
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.newResourceAddress(ResourceAddressFactorySpi.java:127)
	at org.kaazing.gateway.resource.address.ResourceAddressFactory.newResourceAddress(ResourceAddressFactory.java:155)
	at org.kaazing.gateway.transport.ssl.VirtualHostKeySelectorTest.shouldGetVirtualHostMatchingHostAlias(VirtualHostKeySelectorTest.java:363)

shouldGetVirtualHostMatchingHostAlias2(org.kaazing.gateway.transport.ssl.VirtualHostKeySelectorTest)  Time elapsed: 0.007 sec  <<< ERROR!
java.lang.ClassCastException: java.net.URI cannot be cast to java.lang.String
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.parseNamedOptions(ResourceAddressFactorySpi.java:370)
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.newResourceAddress(ResourceAddressFactorySpi.java:127)
	at org.kaazing.gateway.resource.address.ResourceAddressFactory.newResourceAddress(ResourceAddressFactory.java:155)
	at org.kaazing.gateway.transport.ssl.VirtualHostKeySelectorTest.shouldGetVirtualHostMatchingHostAlias2(VirtualHostKeySelectorTest.java:408)

shouldGetVirtualHostWildcardAlias(org.kaazing.gateway.transport.ssl.VirtualHostKeySelectorTest)  Time elapsed: 0.005 sec  <<< ERROR!
java.lang.ClassCastException: java.net.URI cannot be cast to java.lang.String
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.parseNamedOptions(ResourceAddressFactorySpi.java:370)
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.newResourceAddress(ResourceAddressFactorySpi.java:127)
	at org.kaazing.gateway.resource.address.ResourceAddressFactory.newResourceAddress(ResourceAddressFactory.java:155)
	at org.kaazing.gateway.transport.ssl.VirtualHostKeySelectorTest.shouldGetVirtualHostWildcardAlias(VirtualHostKeySelectorTest.java:452)
```

**Comment by sbadugu** [comment]
@cmebarrow I see that you'r PR has been merged. Can we close this issue ?

**Comment by jitsni** [comment]
Yes, we can close this one.
