### ISSUE TITLE
WsxAcceptorLoggingIT.shouldLogOpenWriteReceivedAndClose fails

### ISSUE THREAD

**Issue by jitsni** [kaazing/gateway#459]
https://s3.amazonaws.com/archive.travis-ci.org/jobs/116736364/log.txt :

```
shouldLogOpenWriteReceivedAndClose(org.kaazing.gateway.transport.wsn.logging.WsxAcceptorLoggingIT) starting
INFO [tcp#38 127.0.0.1:47192] OPENED: (#00000038: kaazing niosocketchannel, server, /127.0.0.1:47192 => /127.0.0.1:8080)
TRACE [tcp#38 127.0.0.1:47192] RECEIVED: REQUEST: HTTP/1.1 GET /path HEADERS: {Upgrade=[websocket], Sec-WebSocket-Version=[13], Sec-WebSocket-Protocol=[x-kaazing-handshake], Sec-WebSocket-Key=[dGhlIHNhbXBsZSBub25jZQ==], Host=[localhost:8080], Connection=[Upgrade]} null 
INFO [http#39 127.0.0.1:47192] OPENED: (#00000039: kzg http, server, http://localhost:8080/path => http://localhost:8080/path)
TRACE [tcp#38 127.0.0.1:47192] WRITE: RESPONSE: 101 Web Socket Protocol Handshake HTTP/1.1 HEADERS: {Connection=[Upgrade], Date=[Thu, 17 Mar 2016 20:16:45 GMT], Sec-WebSocket-Accept=[s3pPLMBiTxaQ9kYGzzhZRbK+xOo=], Sec-WebSocket-Protocol=[x-kaazing-handshake], Server=[Kaazing Gateway], Upgrade=[websocket]} CONTENT: HeapBuffer[pos=0 lim=0 cap=0: empty]  
TRACE [tcp#38 127.0.0.1:47192] WRITE: CONTENT: HeapBuffer[pos=0 lim=0 cap=0: empty] 
INFO [http#39 127.0.0.1:47192] CLOSED: (#00000039: kzg http, server, http://localhost:8080/path => http://localhost:8080/path)
TRACE [tcp#38 127.0.0.1:47192] RECEIVED: BINARY: 47 45 54 20 2F 70 61 74 68 20 48 54 54 50 2F 31 2E 31 0D 0A 0D 0A
TRACE [wsn#40 127.0.0.1:47192] RECEIVED: REQUEST: HTTP/1.1 GET /path HEADERS: {X-Next-Protocol=[ws/rfc6455], Upgrade=[websocket], Sec-WebSocket-Version=[13], Sec-WebSocket-Protocol=[], Sec-WebSocket-Key=[dGhlIHNhbXBsZSBub25jZQ==], Host=[localhost:8080], Connection=[Upgrade]} null 
INFO [http#41 127.0.0.1:47192] OPENED: (#00000041: kzg http, server, http://localhost:8080/path => httpx://localhost:8080/path)
TRACE [wsn#40 127.0.0.1:47192] WRITE: RESPONSE: 101 Web Socket Protocol Handshake HTTP/1.1 HEADERS: {Connection=[Upgrade], Date=[Thu, 17 Mar 2016 20:16:45 GMT], Sec-WebSocket-Accept=[s3pPLMBiTxaQ9kYGzzhZRbK+xOo=], Server=[Kaazing Gateway], Upgrade=[websocket]} CONTENT: HeapBuffer[pos=0 lim=0 cap=0: empty]  
TRACE [tcp#38 127.0.0.1:47192] WRITE: BINARY: 48 54 54 50 2F 31 2E 31 20 31 30 31 20 57 65 62 20 53 6F 63 6B 65 74 20 50 72 6F 74 6F 63 6F 6C 20 48 61 6E 64 73 68 61 6B 65 0D 0A 43 6F 6E 6E 65 63 74 69 6F 6E 3A 20 55 70 67 72 61 64 65 0D 0A 44 61 74 65 3A 20 54 68 75 2C 20 31 37 20 4D 61 72 20 32 30 31 36 20 32 30 3A 31 36 3A 34 35 20 47 4D 54 0D 0A 53 65 63 2D 57 65 62 53 6F 63 6B 65 74 2D 41 63 63 65 70 74 3A 20 73 33 70 50 4C 4D 42 69 54 78 61 51 39 6B 59 47 7A 7A 68 5A 52 62 4B 2B 78 4F 6F 3D 0D 0A 53 65 72 76 65 72 3A 20 4B 61 61 7A 69 6E 67 20 47 61 74 65 77 61 79 0D 0A 55 70 67 72 61 64 65 3A 20 77 65 62 73 6F 63 6B 65 74 0D 0A 0D 0A
TRACE [wsn#40 127.0.0.1:47192] WRITE: CONTENT: HeapBuffer[pos=0 lim=0 cap=0: empty] 
INFO [wsn#42 127.0.0.1:47192] OPENED: (#00000042: kzg wsn, server, ws://localhost:8080/path => wsx://localhost:8080/path)
INFO [http#41 127.0.0.1:47192] CLOSED: (#00000041: kzg http, server, http://localhost:8080/path => httpx://localhost:8080/path)
TRACE [tcp#38 127.0.0.1:47192] RECEIVED: TEXT: 41 41 41
TRACE [wsn#40 127.0.0.1:47192] RECEIVED: TEXT: 41 41 41
TRACE [wsn#42 127.0.0.1:47192] RECEIVED: HeapBuffer[pos=0 lim=3 cap=3: 41 41 41]
TRACE [wsn#42 127.0.0.1:47192] WRITE: HeapBuffer[pos=0 lim=3 cap=3: 41 41 41]
TRACE [wsn#40 127.0.0.1:47192] WRITE: TEXT: 41 41 41
TRACE [tcp#38 127.0.0.1:47192] WRITE: TEXT: 41 41 41
TRACE [tcp#38 127.0.0.1:47192] RECEIVED: CLOSE: status=1005, reason=null
TRACE [tcp#38 127.0.0.1:47192] WRITE: CLOSE: status=1005, reason=null
DEBUG [ws/#40] Logout successful.
WsxAcceptorLoggingIT.shouldLogOpenWriteReceivedAndClose FAILED with exception java.lang.AssertionError: Log messages were not as expected
- the following patterns of log messages were not logged: [tcp#.*CLOSED, wsn#.*CLOSED],
only these were logged: [http#.*CLOSED, http#.*OPENED, tcp#.*OPENED, tcp#.*RECEIVED, tcp#.*WRITE, wsn#.*OPENED, wsn#.*RECEIVED, wsn#.*WRITE] (0.37 secs)
java.lang.AssertionError: Log messages were not as expected
- the following patterns of log messages were not logged: [tcp#.*CLOSED, wsn#.*CLOSED],
only these were logged: [http#.*CLOSED, http#.*OPENED, tcp#.*OPENED, tcp#.*RECEIVED, tcp#.*WRITE, wsn#.*OPENED, wsn#.*RECEIVED, wsn#.*WRITE]
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.kaazing.test.util.MemoryAppender.assertMessagesLogged(MemoryAppender.java:116)
    at org.kaazing.gateway.transport.wsn.logging.WsxAcceptorLoggingIT.shouldLogOpenWriteReceivedAndClose(WsxAcceptorLoggingIT.java:86)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
    at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by StCostea** [comment]
I have found that this issue is related with the usage of MemoryAppender.assertMessagesLogged with the GatewayRule. It is happening in many other classes (I have found it and investigated it in WsnAcceptorInfoLoggingIT).
The problem is that the k3po rule is sometimes finishing too fast and the gateway is stopped before completing the processing of the message queue.

The solution was to have a retry mechanism with a timeout and to let the gateway finish its processing. I will create a new test rule with this mechanism and I will replace current code with it in all existing places.
