### ISSUE TITLE
HTTP request URI parsing throws URISyntaxException

### ISSUE THREAD

**Issue by jitsni** [kaazing/gateway#51]
JDK's URI class is strict about chars like '|' in query string (I think most of the browsers allow it). The following request from browser to jira fails in http transport.

```
Caused by: java.net.URISyntaxException: Illegal character in query at index 37: /logout?atl_token=BBWF-YPLZ-8CC3-XLLR|a17b2ee0a53d92ac67bade03d640b8745a8ff157|lin
    at java.net.URI$Parser.fail(URI.java:2829)
    at java.net.URI$Parser.checkChars(URI.java:3002)
    at java.net.URI$Parser.parseHierarchical(URI.java:3092)
    at java.net.URI$Parser.parse(URI.java:3044)
    at java.net.URI.<init>(URI.java:595)
    at org.kaazing.gateway.transport.http.bridge.filter.HttpRequestLineDecodingState$4.finishDecode(HttpRequestLineDecodingState.java:140)
    at org.kaazing.mina.filter.codec.statemachine.ConsumeToDynamicTerminatorDecodingState.decode(ConsumeToDynamicTerminatorDecodingState.java:111)
    at org.kaazing.gateway.transport.DecodingStateMachine.decode(DecodingStateMachine.java:91)
    at org.kaazing.gateway.transport.DecodingStateMachine.decode(DecodingStateMachine.java:91)
    at org.kaazing.gateway.transport.DecodingStateMachine.decode(DecodingStateMachine.java:91)
    at org.kaazing.gateway.transport.http.bridge.filter.HttpRequestDecodingState.decode(HttpRequestDecodingState.java:340)
    at org.kaazing.gateway.transport.http.bridge.filter.HttpMessageDecoder.decode(HttpMessageDecoder.java:39)
    at org.kaazing.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:240)
    ... 23 more
```

**Comment by dpwspoon** [comment]
Is this with the http.proxy?

**Comment by jitsni** [comment]
It can happen with any HTTP request.
