### ISSUE TITLE
transport.wsn DuplicateBindTest: test timed out

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#58]
Happened in [build 44](https://travis-ci.org/kaazing/gateway/builds/54656080) of pull request #57 on openjdk although the pull request makes no related changes so I suspect it's a general sporadic failure. This is confirmed: same failure happened in [build 33](https://travis-ci.org/kaazing/gateway/builds/53702367) on oraclejdk, see [log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/53702368/log.txt).
```
Running org.kaazing.gateway.transport.wsn.DuplicateBindTest
log4j:WARN No appenders could be found for logger (org.kaazing.gateway.server.context.resolve.DefaultSecurityContext).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.13 sec <<< FAILURE!
connectingOnService1ShouldNotGetAccessToService2(org.kaazing.gateway.transport.wsn.DuplicateBindTest)  Time elapsed: 2.011 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 2000 milliseconds
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1295)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1248)
	at java.net.InetAddress.getAllByName(InetAddress.java:1164)
	at java.net.InetAddress.getAllByName(InetAddress.java:1098)
	at org.kaazing.gateway.resource.address.ResourceAddress$ResolverOption$1.getAllByName(ResourceAddress.java:504)
	at org.kaazing.gateway.resource.address.tcp.TcpResourceAddressFactorySpi.newResourceAddresses0(TcpResourceAddressFactorySpi.java:151)
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.newResourceAddress(ResourceAddressFactorySpi.java:131)
	at org.kaazing.gateway.resource.address.ResourceAddressFactory.newResourceAddress(ResourceAddressFactory.java:168)
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.parseNamedOptions(ResourceAddressFactorySpi.java:400)
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.newResourceAddress(ResourceAddressFactorySpi.java:128)
	at org.kaazing.gateway.resource.address.ResourceAddressFactory.newResourceAddress(ResourceAddressFactory.java:168)
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.parseNamedOptions(ResourceAddressFactorySpi.java:400)
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.newResourceAddress(ResourceAddressFactorySpi.java:128)
	at org.kaazing.gateway.resource.address.ResourceAddressFactory.newResourceAddress(ResourceAddressFactory.java:168)
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.parseNamedOptions(ResourceAddressFactorySpi.java:400)
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.newResourceAddress(ResourceAddressFactorySpi.java:128)
	at org.kaazing.gateway.resource.address.ResourceAddressFactory.newResourceAddress(ResourceAddressFactory.java:168)
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.parseNamedOptions(ResourceAddressFactorySpi.java:400)
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.newResourceAddress(ResourceAddressFactorySpi.java:128)
	at org.kaazing.gateway.resource.address.ResourceAddressFactory.newResourceAddress(ResourceAddressFactory.java:160)
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.newResourceAddressWithAlternate(ResourceAddressFactorySpi.java:416)
	at org.kaazing.gateway.resource.address.ws.WsResourceAddressFactorySpi.setAlternateOption(WsResourceAddressFactorySpi.java:173)
	at org.kaazing.gateway.resource.address.ResourceAddressFactorySpi.newResourceAddress(ResourceAddressFactorySpi.java:107)
	at org.kaazing.gateway.resource.address.ResourceAddressFactory.newResourceAddress(ResourceAddressFactory.java:160)
	at org.kaazing.gateway.server.context.resolve.DefaultServiceContext.bind(DefaultServiceContext.java:528)
	at org.kaazing.gateway.server.context.resolve.DefaultServiceContext.bind(DefaultServiceContext.java:441)
	at org.kaazing.gateway.service.echo.EchoService.start(EchoService.java:64)
	at org.kaazing.gateway.server.context.resolve.DefaultServiceContext.start(DefaultServiceContext.java:1007)
	at org.kaazing.gateway.server.Launcher.initInternal(Launcher.java:84)
	at org.kaazing.gateway.server.Launcher.init(Launcher.java:54)
	at org.kaazing.gateway.server.test.Gateway.start(Gateway.java:103)
	at org.kaazing.gateway.transport.wsn.DuplicateBindTest.connectingOnService1ShouldNotGetAccessToService2(DuplicateBindTest.java:44)

```

**Comment by sbadugu** [comment]
This test has been removed and it doesn't show anymore in the latest workspace.
