### ISSUE TITLE
transport.wsn.UnresolvableHostnameIT

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#59]
Happened in [build 44](https://travis-ci.org/kaazing/gateway/builds/54656080) of pull request #57 on openjdk although the pull request makes no related changes so I suspect it's a general sporadic failure.

Running org.kaazing.gateway.transport.wsn.UnresolvableHostnameIT
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.201 sec <<< FAILURE! - in org.kaazing.gateway.transport.wsn.UnresolvableHostnameIT
connectingOnService1ShouldNotGetAccessToService2(org.kaazing.gateway.transport.wsn.UnresolvableHostnameIT)  Time elapsed: 0.198 sec  <<< FAILURE!
org.junit.ComparisonFailure: Specified behavior did not match expected:<...ndGatewayStartsUp)

[connect tcp://127.0.0.1:51111
connected

close
closed]
> but was:<...ndGatewayStartsUp)

[]
>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.kaazing.k3po.junit.rules.SpecificationStatement.evaluate(SpecificationStatement.java:103)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.RuntimeException: Error binding to ws://unresolvable.kaazing.me:8000/: Unable to bind resource: tcp://127.0.0.1:51111 cause: Unable to bind address: /127.0.0.1:51111
	at org.kaazing.gateway.server.context.resolve.DefaultServiceContext.bindInternal(DefaultServiceContext.java:807)
	at org.kaazing.gateway.server.context.resolve.DefaultServiceContext.bind(DefaultServiceContext.java:530)
	at org.kaazing.gateway.server.context.resolve.DefaultServiceContext.bind(DefaultServiceContext.java:441)
	at org.kaazing.gateway.service.echo.EchoService.start(EchoService.java:64)

**Comment by dpwspoon** [comment]
@cmebarrow This is fixed via your pull request, correct?  kaazing/gateway#57

**Comment by cmebarrow** [comment]
Yes
