### ISSUE TITLE
SseSameOriginIT.sseIe8HttpxeConnectAndGetData sometimes fails

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#60]
on my Windows 7 box. 

Running org.kaazing.gateway.transport.sse.SseSameOriginIT
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.19 sec <<< FAILURE! - in org.kaazing.gateway.transport.sse.SseSameOriginIT

sseIe8HttpxeConnectAndGetData(org.kaazing.gateway.transport.sse.SseSameOriginIT)  Time elapsed: 0.08 sec  <<< FAILURE!
org.junit.ComparisonFailure: Specified behavior did not match expected:<...ad "\n"
read /:.*/ "[\n"
read "\n"
read "data:Kobe is greater than Griffen\n"
read "\n"

close
closed]
> but was:<...ad "\n"
read /:.*/ "[ "]
>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.kaazing.k3po.junit.rules.SpecificationStatement.evaluate(SpecificationStatement.java:132)
        at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Comment by dpwspoon** [comment]
I believe this was fixed via https://github.com/kaazing/gateway/issues/41.
