### ISSUE TITLE
failure in WsnConnectorTest

### ISSUE THREAD

**Issue by ahousing** [kaazing/gateway#655]
In a build I did on my machine just now, I got the following summary of failures (more details to be attached in logfile):
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 19.799 sec <<< FAILURE! - in org.kaazing.gateway.transport.wsn.WsnTransportTest
connectorShouldWriteAndReceiveMessage(org.kaazing.gateway.transport.wsn.WsnTransportTest)  Time elapsed: 9.83 sec  <<< FAILURE!
java.lang.AssertionError: echo not received
        at org.kaazing.gateway.transport.wsn.WsnTransportTest.waitForLatch(WsnTransportTest.java:305)
        at org.kaazing.gateway.transport.wsn.WsnTransportTest.connectorShouldWriteAndReceiveMessage(WsnTransportTest.java:289)

connectorShouldReceiveMessageFromAcceptor(org.kaazing.gateway.transport.wsn.WsnTransportTest)  Time elapsed: 9.963 sec  <<< FAILURE!
java.lang.AssertionError: message from acceptor not received
        at org.kaazing.gateway.transport.wsn.WsnTransportTest.waitForLatch(WsnTransportTest.java:305)
        at org.kaazing.gateway.transport.wsn.WsnTransportTest.connectorShouldReceiveMessageFromAcceptor(WsnTransportTest.java:233)

Results :

Failed tests:
  WsnConnectorTest.shouldCloseWsnSessionWhenTransportClosesCleanlyButUnexpectedly:216 null
  WsnTransportTest.connectorShouldReceiveMessageFromAcceptor:233->waitForLatch:305 message from acceptor not received
  WsnTransportTest.connectorShouldWriteAndReceiveMessage:289->waitForLatch:305 echo not received

Tests run: 22, Failures: 3, Errors: 0, Skipped: 1

**Comment by ahousing** [comment]
[build.txt](https://github.com/kaazing/gateway/files/382761/build.txt)

**Comment by ahousing** [comment]
See also https://github.com/kaazing/gateway/issues/162

**Comment by ahousing** [comment]
Removing "sporatic" (both label and in subject), as this is consistent* on my machine.  Windows, maven=3.3.3.  (Actually, the last two errors are consistent.  I only got the first error once.)

**Comment by ahousing** [comment]
Note on a docker/unix machine, it went through fine.  This might be windows-specific.
