### ISSUE TITLE
Diagnostic message for unexpected exception in a filter should include session details

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#685]
The following extract from the log files for support ticket 3240 illustrates the need for better information in the message written by [org.apache.mina.util.DefaultExceptionMonitor](https://github.com/kaazing/gateway/blob/5.1.1/mina.core/core/src/main/java/org/apache/mina/util/DefaultExceptionMonitor.java). The message should include details of the IoSession concerned, including client tcp port number, as do the other diagnostic messages.

```
2016-08-19 15:24:58,640 transport.tcp.accept [New I/O worker #3] INFO  [tcp#119775 126.246.166.113:61228] CLOSED: (#00119775: kaazing niosocketchannel, server, /126.246.166.113:61228 => /126.246.166.103:1080)
2016-08-19 15:24:58,639 org.apache.mina.util.DefaultExceptionMonitor [New I/O worker #1] WARN  Unexpected exception.
java.lang.NullPointerException
    at org.kaazing.gateway.transport.wsn.WsCloseFilter$1.operationComplete(WsCloseFilter.java:187)
    at org.kaazing.gateway.transport.wsn.WsCloseFilter$1.operationComplete(WsCloseFilter.java:169)
    at org.kaazing.mina.core.future.DefaultIoFutureEx.notifyListener(DefaultIoFutureEx.java:423)
    at org.kaazing.mina.core.future.DefaultIoFutureEx.notifyListeners(DefaultIoFutureEx.java:411)
    at org.kaazing.mina.core.future.DefaultIoFutureEx.setValue(DefaultIoFutureEx.java:327)
    at org.kaazing.mina.core.future.DefaultWriteFutureEx.setWritten(DefaultWriteFutureEx.java:89)
    at org.kaazing.mina.netty.ChannelWriteFutureListener.setFutureWritten(ChannelWriteFutureListener.java:51)
    at org.kaazing.mina.netty.ChannelWriteFutureListener.operationComplete(ChannelWriteFutureListener.java:41)
...
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:143)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:144)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:348)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:120)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:243)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)


```

**Comment by stanculescu** [comment]
https://github.com/kaazing/gateway/pull/836

**Comment by cmebarrow** [comment]
Closing because PR #836 is now merged.
