### ISSUE TITLE
NullPointerException in WsCloseFilter$1.operationComplete

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#687]
The following extract from the log files for support ticket 3240 shows a NullPointerException in WsCloseFilter occurring immediately after writing a WS_CLOSE frame in response to a received one. This was using Enterprise Gateway release 5.0.2-RC003. 
```
2016-08-19 15:24:58,640 transport.tcp.accept [New I/O worker #3] INFO  [tcp#119775 126.246.166.113:61228] CLOSED: (#00119775: kaazing niosocketchannel, server, /126.246.166.113:61228 => /126.246.166.103:1080)
2016-08-19 15:24:58,639 org.apache.mina.util.DefaultExceptionMonitor [New I/O worker #1] WARN  Unexpected exception.
java.lang.NullPointerException
	at org.kaazing.gateway.transport.wsn.WsCloseFilter$1.operationComplete(WsCloseFilter.java:187)
	at org.kaazing.gateway.transport.wsn.WsCloseFilter$1.operationComplete(WsCloseFilter.java:169)
	at org.kaazing.mina.core.future.DefaultIoFutureEx.notifyListener(DefaultIoFutureEx.java:423)
	at org.kaazing.mina.core.future.DefaultIoFutureEx.notifyListeners(DefaultIoFutureEx.java:411)
	at org.kaazing.mina.core.future.DefaultIoFutureEx.setValue(DefaultIoFutureEx.java:327)
	at org.kaazing.mina.core.future.DefaultWriteFutureEx.setWritten(DefaultWriteFutureEx.java:89)
	at org.kaazing.mina.netty.ChannelWriteFutureListener.setFutureWritten(ChannelWriteFutureListener.java:51)
	at org.kaazing.mina.netty.ChannelWriteFutureListener.operationComplete(ChannelWriteFutureListener.java:41)
...
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:143)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:144)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:348)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:120)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:243)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```
The NPE happens because WsnSession wsnSession = SESSION_KEY.get(session) returns null.

**Comment by cmebarrow** [comment]
Related bug: #685

**Comment by cmebarrow** [comment]
The error.log file in 112_ES.zip from support ticket 4404 contains the same exception stack, showing this bug is also present in 5.1.4-RC005. Here's a copy:

[error.log.txt](https://github.com/kaazing/gateway/files/522709/error.log.txt)

**Comment by sbadugu** [comment]
@cmebarrow Does the related bug #685 fix this issue too ? I am just confirming so that someone doesn't spend time on this issue, if it is already fixed.

**Comment by cmebarrow** [comment]
@sbadugu No, #685 does not fix this issue.

**Comment by StCostea** [comment]
I am not able to reproduce this exception. I have tried to kill the client process or to disable the network interface. Currently I'm trying to throw the error myself from the code. So far, I did not succeed.

Do you have any suggestion on how to reproduce it ?

**Comment by sbadugu** [comment]
@StCostea Please move on to the other tickets, if you can't reproduce it.
