### ISSUE TITLE
java.io.IOException: Broken pipe causes incorrect event reporting in TCP layer

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#688]
The following extract from the log files for support ticket 3240 shows an IOException: Broken pipe being reported in the TCP layer followed by CLOSE at TCP layer followed by an exception stack in the WSN layer:

```
2016-08-19 15:24:58,636 transport.tcp.accept [New I/O worker #1] INFO  [tcp#114707 126.246.166.116:57210] EXCEPTION: java.io.IOException: Broken pipe
2016-08-19 15:24:58,636 transport.wsn.accept [New I/O worker #3] INFO  [wsn#120541 126.246.166.119:47367] CLOSED: (#00120541: kzg wsn, server, ws://126.246.166.103:8000/mq => wsx://126.246.166.103:8000/mq)
2016-08-19 15:24:58,636 transport.wsn.connect [New I/O worker #3] INFO  [wsn#120127 126.246.166.113:61228] CLOSED: (#00120127: kzg wsn, client, ws://126.246.166.103:8000/mq => ws://126.246.166.103:8000/mq)
2016-08-19 15:24:58,636 transport.tcp.accept [New I/O worker #1] INFO  [tcp#114707 126.246.166.116:57210] CLOSED: (#00114707: kaazing niosocketchannel, server, /126.246.166.116:57210 => /126.246.166.103:8000)
2016-08-19 15:24:58,637 transport.wsn.accept [New I/O worker #1] INFO  [wsn#114709 126.246.166.116:57210] EXCEPTION: java.io.IOException: Network connectivity has been lost or transport was closed at other end, caused by java.io.IOException: Broken pipe
java.io.IOException: Broken pipe
    at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
    at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
    at sun.nio.ch.IOUtil.write(IOUtil.java:51)
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
    at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$SharedUnpooledSendBuffer.transferTo(SocketSendBufferPool.java:298)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:245)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:190)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:99)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36)
    at org.kaazing.mina.netty.ChannelIoProcessor.flushNow(ChannelIoProcessor.java:288)
    at org.kaazing.mina.netty.ChannelIoProcessor.flush0(ChannelIoProcessor.java:87)
    at org.kaazing.mina.netty.ChannelIoProcessor.flush0(ChannelIoProcessor.java:50)
    at org.kaazing.mina.core.service.AbstractIoProcessor.flush(AbstractIoProcessor.java:52)
    at org.kaazing.mina.core.service.AbstractIoProcessor.flush(AbstractIoProcessor.java:30)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$HeadFilter.filterWrite(DefaultIoFilterChain.java:667)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callPreviousFilterWrite(DefaultIoFilterChain.java:547)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callPreviousFilterWrite(DefaultIoFilterChainEx.java:173)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.filterWrite(DefaultIoFilterChain.java:857)
    at org.kaazing.mina.filter.codec.ProtocolCodecFilter$ProtocolEncoderOutputImpl.flushWithFuture(ProtocolCodecFilter.java:426)
    at org.kaazing.mina.filter.codec.ProtocolCodecFilter.filterWrite(ProtocolCodecFilter.java:326)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callPreviousFilterWrite(DefaultIoFilterChain.java:547)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callPreviousFilterWrite(DefaultIoFilterChainEx.java:173)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.filterWrite(DefaultIoFilterChain.java:857)
    at org.apache.mina.core.filterchain.IoFilterAdapter.filterWrite(IoFilterAdapter.java:131)
    at org.kaazing.gateway.transport.LoggingFilter.filterWrite(LoggingFilter.java:272)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callPreviousFilterWrite(DefaultIoFilterChain.java:547)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callPreviousFilterWrite(DefaultIoFilterChainEx.java:173)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.filterWrite(DefaultIoFilterChain.java:857)
    at org.kaazing.mina.filter.util.WriteRequestFilterEx.filterWrite(WriteRequestFilterEx.java:64)
    at org.kaazing.gateway.transport.wsn.WsCloseFilter.wsCloseReceived(WsCloseFilter.java:193)
    at org.kaazing.gateway.transport.ws.WsFilterAdapter.messageReceived(WsFilterAdapter.java:44)
    at org.kaazing.gateway.transport.wsn.WsCloseFilter.messageReceived(WsCloseFilter.java:147)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:474)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callNextMessageReceived(DefaultIoFilterChainEx.java:114)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:843)
    at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:115)
    at org.kaazing.gateway.transport.LoggingFilter.messageReceived(LoggingFilter.java:223)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:474)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callNextMessageReceived(DefaultIoFilterChainEx.java:114)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:843)
    at org.kaazing.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:393)
    at org.kaazing.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:252)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:474)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callNextMessageReceived(DefaultIoFilterChainEx.java:114)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:843)
    at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:115)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:474)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callNextMessageReceived(DefaultIoFilterChainEx.java:114)
    at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:466)
    at org.kaazing.mina.netty.IoSessionChannelHandler.messageReceived(IoSessionChannelHandler.java:124)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:143)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:144)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:348)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:120)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:243)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
2016-08-19 15:24:58,639 transport.wsn.accept [New I/O worker #1] INFO  [wsn#114709 126.246.166.116:57210] CLOSED: (#00114709: kzg wsn, server, ws://126.246.166.103:8000/mq => wsn://126.246.166.103:8000/mq)

```

The exception happens because the TCP (nio) layer is reporting messageReceived(ws close frame) after the IOException occurred on the TCP layer. [WsCloseFilter.java](https://github.com/kaazing/gateway/blob/5.1.1/transport/wsn/src/main/java/org/kaazing/gateway/transport/wsn/WsCloseFilter.java) correctly attempts to write a WS_CLOSE frame in response, but that fails with another IOException: Broken pipe because the TCP connection is dead.
Here is one of the gateway log files containing this exception:

[error.log.txt](https://github.com/kaazing/gateway/files/437853/error.log.txt)

The bug is in the TCP layer. It should not be reporting data read after reporting the exception and session closed events. The offending code is in the Netty layer [NioWorker.java](https://github.com/kaazing/gateway/blob/5.1.1/mina.netty/src/main/java/org/jboss/netty/channel/socket/nio/NioWorker.java). In the read method, the `if (readBytes > 0) { ... fireMessageReceived` block should be done inside the try catch block above so message received is not reported when an exception occurs.

**Comment by cmebarrow** [comment]
Related bugs: #687, #685
