### ISSUE TITLE
RC releases: Gateway fails to start up due to error in Update service concerning version format

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#715]
To reproduce:
- Install enterprise gateway release 5.1.4-RC002 (or gateway 5.2.4-RC001) by uncompressing the distribution zip/gz
- Start the gateway. Observe this fails:
```
INFO  Kaazing Gateway (5.1.4-RC002)
INFO  Configuration file: C:\JMSGateway\kaazing-enterprise-gateway-5.1.4-RC002\conf\gateway-config.xml
INFO  Checking license information
INFO    No valid Kaazing license found
INFO  Using Kaazing developer license, maximum 100 connections
ERROR Gateway failed to launch
java.lang.RuntimeException: Could not locate a product version associated with the jars on the classpath
        at org.kaazing.gateway.service.update.check.UpdateCheckService.<init>(UpdateCheckService.java:60)
        at org.kaazing.gateway.service.update.check.UpdateCheckServiceFactorySpi.newService(UpdateCheckServiceFactorySpi.java:35)
        at org.kaazing.gateway.service.ServiceFactory.newService(ServiceFactory.java:49)
        at org.kaazing.gateway.server.context.resolve.GatewayContextResolver.resolveServices(GatewayContextResolver.java:491)
        at org.kaazing.gateway.server.context.resolve.GatewayContextResolver.resolve(GatewayContextResolver.java:236)
        at org.kaazing.gateway.server.impl.GatewayImpl.launch(GatewayImpl.java:305)
        at org.kaazing.gateway.server.GatewayCommandLineProcessor.launchGateway(GatewayCommandLineProcessor.java:112)
        at org.kaazing.gateway.server.GatewayCommandLineProcessor.launchGateway(GatewayCommandLineProcessor.java:57)
        at org.kaazing.gateway.server.WindowsMain.main(WindowsMain.java:59)
Caused by: java.lang.IllegalArgumentException: version String is not of form (?<major>[0-9]+)\.(?<minor>[0-9]+)\.(?<patch>[0-9]+)
        at org.kaazing.gateway.service.update.check.GatewayVersion.parseGatewayVersion(GatewayVersion.java:83)
        at org.kaazing.gateway.service.update.check.UpdateCheckService.<init>(UpdateCheckService.java:58)
        ... 8 more
```
Workaround: remove the update.check service element

**Comment by sbadugu** [comment]
@Anisotrop Please address this issue ASAP in the current sprint. If you don't have enough bandwidth to address this issue, can you please assign it to someone else in the team ? Thanks !

**Comment by Anisotrop** [comment]
The following [PR](https://github.com/kaazing/gateway/pull/716) should fix the issue, @sbadugu please assign it for review.
