### ISSUE TITLE
wseb TextIT.shouldEchoFrameWithPayloadLength128 fails sometimes

### ISSUE THREAD

**Issue by jitsni** [kaazing/gateway#729]
Failed tests: 
  TextIT.shouldEchoFrameWithPayloadLength128 Specified behavior did not match expected:<...length
write close

[read status "200" /.+/
read header "Content-Type" "application/octet-stream"
read header "Connection" "close"

read [0x81 0x81 0x00] ${client128}]

# Upstream
connect...> but was:<...length
write close

[]

# Upstream
connect...>

**Comment by jitsni** [comment]
It fails for this sequence:
- Upstream connects and writes 128 bytes
- k3po closes upstream as upstream is not reading any HTTP status
- WsebUpstreamHandler catches this i/o exception and closes WSEB session
So downstream doesn't get any response.
```
java.io.IOException: Network connectivity has been lost or transport was closed at other end
	at org.kaazing.gateway.transport.wseb.WsebUpstreamHandler.doSessionClosed(WsebUpstreamHandler.java:184)
	at org.kaazing.gateway.transport.wseb.WsebUpstreamHandler.doSessionClosed(WsebUpstreamHandler.java:44)
	at org.kaazing.gateway.transport.IoHandlerAdapter.sessionClosed(IoHandlerAdapter.java:63)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$TailFilter.sessionClosed(DefaultIoFilterChain.java:706)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callNextSessionClosed(DefaultIoFilterChain.java:433)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callNextSessionClosed(DefaultIoFilterChainEx.java:87)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.sessionClosed(DefaultIoFilterChain.java:825)
	at org.apache.mina.core.filterchain.IoFilterAdapter.sessionClosed(IoFilterAdapter.java:91)
	at org.kaazing.gateway.transport.LoggingFilter.sessionClosed(LoggingFilter.java:259)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callNextSessionClosed(DefaultIoFilterChain.java:433)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callNextSessionClosed(DefaultIoFilterChainEx.java:87)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.sessionClosed(DefaultIoFilterChain.java:825)
	at org.kaazing.mina.filter.codec.ProtocolCodecFilter.sessionClosed(ProtocolCodecFilter.java:366)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callNextSessionClosed(DefaultIoFilterChain.java:433)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callNextSessionClosed(DefaultIoFilterChainEx.java:87)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.sessionClosed(DefaultIoFilterChain.java:825)
	at org.apache.mina.core.filterchain.IoFilterAdapter.sessionClosed(IoFilterAdapter.java:91)
	at org.kaazing.mina.core.filterchain.AssertAlignedFilter.sessionClosed(AssertAlignedFilter.java:109)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callNextSessionClosed(DefaultIoFilterChain.java:433)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callNextSessionClosed(DefaultIoFilterChainEx.java:87)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.sessionClosed(DefaultIoFilterChain.java:825)
	at org.apache.mina.core.filterchain.IoFilterAdapter.sessionClosed(IoFilterAdapter.java:91)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callNextSessionClosed(DefaultIoFilterChain.java:433)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callNextSessionClosed(DefaultIoFilterChainEx.java:87)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.fireSessionClosed(DefaultIoFilterChain.java:426)
	at org.apache.mina.core.service.IoServiceListenerSupport.fireSessionDestroyed(IoServiceListenerSupport.java:206)
	at org.kaazing.gateway.transport.AbstractBridgeProcessor.doFireSessionDestroyed(AbstractBridgeProcessor.java:82)
	at org.kaazing.gateway.transport.AbstractBridgeProcessor.remove0(AbstractBridgeProcessor.java:74)
	at org.kaazing.gateway.transport.AbstractBridgeProcessor.remove0(AbstractBridgeProcessor.java:39)
	at org.kaazing.mina.core.service.AbstractIoProcessor.remove(AbstractIoProcessor.java:62)
	at org.kaazing.mina.core.service.AbstractIoProcessor.remove(AbstractIoProcessor.java:30)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$HeadFilter.filterClose(DefaultIoFilterChain.java:675)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callPreviousFilterClose(DefaultIoFilterChain.java:564)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callPreviousFilterClose(DefaultIoFilterChainEx.java:190)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.filterClose(DefaultIoFilterChain.java:863)
	at org.apache.mina.core.filterchain.IoFilterAdapter.filterClose(IoFilterAdapter.java:139)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callPreviousFilterClose(DefaultIoFilterChain.java:564)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callPreviousFilterClose(DefaultIoFilterChainEx.java:190)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.filterClose(DefaultIoFilterChain.java:863)
	at org.apache.mina.core.filterchain.IoFilterAdapter.filterClose(IoFilterAdapter.java:139)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callPreviousFilterClose(DefaultIoFilterChain.java:564)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callPreviousFilterClose(DefaultIoFilterChainEx.java:190)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.filterClose(DefaultIoFilterChain.java:863)
	at org.apache.mina.core.filterchain.IoFilterAdapter.filterClose(IoFilterAdapter.java:139)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callPreviousFilterClose(DefaultIoFilterChain.java:564)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callPreviousFilterClose(DefaultIoFilterChainEx.java:190)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.filterClose(DefaultIoFilterChain.java:863)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain$TailFilter.filterClose(DefaultIoFilterChain.java:781)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.callPreviousFilterClose(DefaultIoFilterChain.java:564)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChainEx.callPreviousFilterClose(DefaultIoFilterChainEx.java:190)
	at org.kaazing.mina.core.filterchain.DefaultIoFilterChain.fireFilterClose(DefaultIoFilterChain.java:557)
	at org.kaazing.mina.core.session.AbstractIoSession.close(AbstractIoSession.java:260)
	at org.kaazing.mina.core.session.AbstractIoSession.close(AbstractIoSession.java:247)
	at org.kaazing.gateway.transport.wseb.WsebUpstreamHandler.doExceptionCaught(WsebUpstreamHandler.java:175)
	at org.kaazing.gateway.transport.wseb.WsebUpstreamHandler.doExceptionCaught(WsebUpstreamHandler.java:44)
```
