### ISSUE TITLE
ClassCastException in ServiceManagementBean$DefaultServiceManagementBean.doSessionCreated

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#733]
This error is seen in error (4).log attached to support ticket 4404. Here's is a extract:

```
2016-10-11 09:21:31,619 [New I/O worker #1] ERROR Exception during upgrade
java.lang.RuntimeException: Exception adding new management session for session: (#00025597: kzg wsn, server, ws://126.246.166.112:8000/mq => ws://126.246.166.112:8000/mq)
    at org.kaazing.gateway.management.context.ManagementGatewayObserver$1.initializeSession(ManagementGatewayObserver.java:116)
    at org.kaazing.gateway.management.context.ManagementGatewayObserver$1.initializeSession(ManagementGatewayObserver.java:105)
    at org.kaazing.gateway.server.context.resolve.DefaultServiceContext$2.initializeSession(DefaultServiceContext.java:839)
    at org.kaazing.gateway.server.context.resolve.DefaultServiceContext$2.initializeSession(DefaultServiceContext.java:831)
    at org.kaazing.gateway.transport.wsn.WsnAcceptor$2.initializeSession(WsnAcceptor.java:291)
    at org.kaazing.gateway.transport.AbstractBridgeAcceptor.finishSessionInitialization0(AbstractBridgeAcceptor.java:182)
    at org.kaazing.mina.core.service.AbstractIoService.initSession(AbstractIoService.java:522)
    at org.kaazing.gateway.transport.AbstractBridgeService.newSession(AbstractBridgeService.java:88)
    at org.kaazing.gateway.transport.AbstractBridgeService.newSession(AbstractBridgeService.java:75)
    at org.kaazing.gateway.transport.wsn.WsnAcceptor.access$1300(WsnAcceptor.java:141)
    at org.kaazing.gateway.transport.wsn.WsnAcceptor$4.doSessionOpened(WsnAcceptor.java:526)
    at org.kaazing.gateway.transport.wsn.WsnAcceptor$4.doSessionOpened(WsnAcceptor.java:481)
...
Caused by: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
    at java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1819)
    at java.util.HashMap$TreeNode.treeify(HashMap.java:1936)
    at java.util.HashMap.treeifyBin(HashMap.java:771)
    at java.util.HashMap.putVal(HashMap.java:643)
    at java.util.HashMap.put(HashMap.java:611)
    at java.util.HashSet.add(HashSet.java:219)
    at org.kaazing.gateway.management.service.ServiceManagementBean$DefaultServiceManagementBean.doSessionCreated(ServiceManagementBean.java:671)
    at org.kaazing.gateway.management.service.CollectOnlyManagementServiceStrategy.doSessionCreated(CollectOnlyManagementServiceStrategy.java:35)
    at org.kaazing.gateway.management.filter.ServiceOnlyManagementFilterStrategy.doSessionCreated(ServiceOnlyManagementFilterStrategy.java:48)
    at org.kaazing.gateway.management.filter.FullManagementFilterStrategy.doSessionCreated(FullManagementFilterStrategy.java:48)
    at org.kaazing.gateway.management.filter.ManagementFilter.newManagementSession(ManagementFilter.java:109)
    at org.kaazing.gateway.management.context.ManagementGatewayObserver$1.initializeSession(ManagementGatewayObserver.java:114)
    ... 240 more
```

Here's a copy of full error log:
[error (4).log.txt](https://github.com/kaazing/gateway/files/522803/error.4.log.txt)

**Comment by cmebarrow** [comment]
According to http://stackoverflow.com/questions/29967401/strange-hashmap-exception-hashmapnode-cannot-be-cast-to-hashmaptreenode, this is due to incorrect use of HashMap from multiple threads. HashMap is not thread-safe. We should be using something like ConcurrentHashMap instead.

**Comment by cmebarrow** [comment]
The exception occurs when accessing the following member variable in method `ServiceManagementBean$DefaultServiceManagementBean.doSessionCreated`:

```
private Set<Long> sessionCreatedFlag = new HashSet<>();
```

We should use a ConcurrentHashMap instead.

**Comment by cmebarrow** [comment]
Fix is included in PR https://github.com/kaazing/gateway/pull/784

**Comment by cmebarrow** [comment]
Closing because PR #784 is now merged
