### ISSUE TITLE
WsxAcceptorLoggingIT.shouldLogOpenAndInactivityTimeoutClose fails

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#737]
This happened in two Travis builds recently, for example https://travis-ci.org/cmebarrow/gateway/builds/167208840. The relevant portion of the build output is attached:
[WsxAcceptorLoggingIT.fail.txt](https://github.com/kaazing/gateway/files/527783/WsxAcceptorLoggingIT.fail.txt)

Here is an extract:
```
WsxAcceptorLoggingIT.shouldLogOpenAndInactivityTimeoutClose FAILED with exception java.lang.Exception: GET LOG (2.06 secs)
java.lang.Exception: GET LOG
	at org.kaazing.gateway.transport.wsn.logging.WsxAcceptorLoggingIT.shouldLogOpenAndInactivityTimeoutClose(WsxAcceptorLoggingIT.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cmebarrow** [comment]
This was a temporary change I did in my branch to test logging! Not a bug in the product.
