### ISSUE TITLE
JMX management service: closeSessions (by principal) service bean method causes NPEs

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#783]
This is reproducible sporadically in JmxSessionPrincipalIT.shouldKillSessionsByRolePrincipal.  Running with debugging you can see the following NPE thrown when the session is attempted to be fetched via a value from a <Principal, SessionId> map via `serviceManagementBean.removeSessionManagementBean(sessionId)`.  I believe the serviceManagementBean has not been populated with the new session yet returning the NPE.  Guarding against the NPE (by not doing anything if it is null) will result in the session not being closed

```
1825 org.kaazing.gateway.management.session.SessionManagementBeanImpl [management-1] WARN  SessionManagementBeanImpl  - Error during doSessionClosed session listener notifications:
java.lang.NullPointerException
	at org.kaazing.gateway.management.jmx.JmxSessionManagementListener.doSessionClosed(JmxSessionManagementListener.java:67)
	at org.kaazing.gateway.management.session.SessionManagementBeanImpl$2.run(SessionManagementBeanImpl.java:287)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
...
```

**Comment by cmebarrow** [comment]
The issue probably is that member variable sessionBeanMap in JmxManagementServiceHandler is not thread safe. It is initialized as follows: `sessionBeanMap = new HashMap<>();`
Debugging in the test confirms that member variable and serviceBeanMap exist from multiple threads.
Solution would be to use ConcurrentHashMap instead for both of these variables.
I have make this change in my [management_fixes](https://github.com/cmebarrow/gateway/tree/management_fixes) branch.

**Comment by cmebarrow** [comment]
Using ConcurrentHashMap, although necessary I believe, did not resolve the issue. I can still the NPEs if I turn on logging in for example JmxSessionPrincipalsIT.shouldKillSessionsByRolePrincipalSupertype()

**Comment by cmebarrow** [comment]
The sequence is:
- RMI Thread: ServiceMXBeanImpl.closeSessions calls sessionBean.close() 
- IO Thread Management.doFilterClose calls FullManagementFilterStrategy.doSessionClosed which:
  - calls managementContext.removeSessionManagementBean which causes the sessionBean to be removed from the sessionBeanMap in JmxManagementServiceHandler
  - calls FullManagementSessionStrategy.doSessionClosed which calls sessionBean.doSessionClosedListeners which spawns a task into the management background thread to fire the sessionBean's management listeners
- Management thread hits NPE in JmxSessionManagementListener because it does managementServiceHandler.getSessionMXBean which returns null

**Comment by cmebarrow** [comment]
Closing, fixed by https://github.com/kaazing/gateway/pull/790
