### ISSUE TITLE
HTTP request decoder exception during method decoding (sporadic)

### ISSUE THREAD

**Issue by jitsni** [kaazing/gateway#806]
```
Caused by: java.lang.IllegalStateException: Current state = RESET, new state = CODING_END
	at java.nio.charset.CharsetDecoder.throwIllegalStateException(CharsetDecoder.java:992)
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:572)
	at org.kaazing.mina.core.buffer.AbstractIoBufferEx.getString(AbstractIoBufferEx.java:1560)
	at org.kaazing.gateway.transport.http.bridge.filter.HttpRequestLineDecodingState$2.finishDecode(HttpRequestLineDecodingState.java:96)
	at org.kaazing.mina.filter.codec.statemachine.ConsumeToDynamicTerminatorDecodingState.decode(ConsumeToDynamicTerminatorDecodingState.java:105)
	at org.kaazing.gateway.transport.DecodingStateMachine.decode(DecodingStateMachine.java:88)
	at org.kaazing.gateway.transport.DecodingStateMachine.decode(DecodingStateMachine.java:88)
	at org.kaazing.gateway.transport.DecodingStateMachine.decode(DecodingStateMachine.java:88)
	at org.kaazing.gateway.transport.http.bridge.filter.HttpRequestDecodingState.decode(HttpRequestDecodingState.java:365)
	at org.kaazing.gateway.transport.http.bridge.filter.HttpMessageDecoder.decode(HttpMessageDecoder.java:34)
	at org.kaazing.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:249)
	... 31 more
```

The buffer is
```
org.apache.mina.filter.codec.ProtocolDecoderException: java.lang.IllegalStateException: Current state = RESET, new state = CODING_END (Hexdump: 50 4F 53 54 20 2F 70 61 74 68 2F 3B 65 2F 75 62 6D 2F 4B 36 76 42 42 66 4B 75 32 68 45 50 6D 71 4C 58 4F 4C 37 39 59 6F 38 52 46 58 62 37 58 32 49 4F 3F 71 75 65 72 79 20 48 54 54 50 2F 31 2E 31 0D 0A 48 6F 73 74 3A 20 6C 6F 63 61 6C 68 6F 73 74 3A 38 30 38 30 0D 0A 43 6F 6E 74 65 6E 74 2D 54 79 70 65 3A 20 61 70 70 6C 69 63 61 74 69 6F 6E 2F 6F 63 74 65 74 2D 73 74 72 65 61 6D 0D 0A 58 2D 53 65 71 75 65 6E 63 65 2D 4E 6F 3A 20 31 37 0D 0A 43 6F 6E 74 65 6E 74 2D 4C 65 6E 67 74 68 3A 20 32 32 0D 0A 0D 0A 00 F3 8F 9D B0 E7 9E B8 7B 17 F3 81 94 85 5B E5 80 AF E7 AC 91 FF)
```

**Comment by jitsni** [comment]
This PR https://github.com/kaazing/gateway/pull/808 may fix this. But I couldn't reproduce the issue so not sure.
