### ISSUE TITLE
Build failure in mina.netty on Travis: NioSocketIT.testBindAsync, NioSocketChannelIoAcceptorIT.disposeShouldStopAll_IO_Threads

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#824]
This issue was first reported in tickets 161: "travis build for gateway giving various errors".  It just happened again when building PR #823 (commit 2ead3a37). Build output:
[NioSocketChannelIoAcceptorIT.fail.txt](https://github.com/kaazing/gateway/files/652494/NioSocketChannelIoAcceptorIT.fail.txt)

Extract:
```
Failed tests: 
  NioSocketChannelIoAcceptorIT.disposeShouldStopAll_IO_Threads:218->assertNoWorkerThreads:322 No worker or boss threads should be running after disposeResources, found 3 workers, 0 bosses: [New I/O worker #31, New I/O worker #32, New I/O worker #33]
Tests in error: 
org.kaazing.mina.netty.NioSocketIT.testBindAsync(org.kaazing.mina.netty.NioSocketIT)
  Run 1: NioSocketIT.testBindAsync:384->Object.wait:502->Object.wait:-2 Â» TestTimedOut ...
  Run 2: NioSocketIT.testBindAsync Â»  Appears to be stuck in thread New I/O worker #32
```

**Comment by cmebarrow** [comment]
The first test failure was:
```
NioSocketIT.testBindAsync FAILED with exception org.junit.runners.model.MultipleFailureException: 
There were 2 errors:
  org.junit.runners.model.TestTimedOutException(test timed out after 15 seconds)
  java.lang.Exception(Appears to be stuck in thread New I/O worker #32) (15.00 secs)
org.junit.runners.model.MultipleFailureException: There were 2 errors:
  org.junit.runners.model.TestTimedOutException(test timed out after 15 seconds)
  java.lang.Exception(Appears to be stuck in thread New I/O worker #32)
	at org.junit.internal.runners.statements.FailOnTimeout.createTimeoutException(FailOnTimeout.java:169)
	at org.junit.internal.runners.statements.FailOnTimeout.getResult(FailOnTimeout.java:152)
	at org.junit.internal.runners.statements.FailOnTimeout.evaluate(FailOnTimeout.java:128)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
```
